### ISSUE TITLE
Allow setting value for `prompt`

### ISSUE THREAD

**Issue by Ethan-Hill** [Bioblaze/passport-discord.js#5]
Discord's OAuth has a parameter prompt which allows you to control if a user is displayed the consent screen or not.

prompt controls how the authorization flow handles existing authorizations. If a user has previously authorized your application with the requested scopes and prompt is set to consent, it will request them to reapprove their authorization. If set to none, it will skip the authorization screen and redirect them back to your redirect URI without requesting their authorization.

Allowing devs to set this value would be useful for websites that might have frequent traffic from consistent users.

**Comment by Bioblaze** [comment]
ohhh ok XD my bad I will add it in, let me find the help.
